# Site settings
title: Hungry for Homemade.
email: hfhomemade@gmail.com
description: "Hungry for Homemade."
baseurl: ""
url: "http://hungryforhomemade.com"

# Build settings
markdown: kramdown
permalink: pretty
